language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm start
  - npm test
  - npm run build


  # safelist
branches:
  only:
  - frontend_login_authentication_api