matrix:
  include:
      - language: node_js
        
        node_js:
          - "stable"
        
        cache:
        directories:
          - node_modules
        
        script:
          - cd frontend/todo-app
          - npm test


      - language: java
      
        jdk:
          - oraclejdk9


          