matrix:
  include:
      - language: node_js
        
        node_js:
          - "stable"
        
        cache:
        directories:
          - node_modules
        
        script:
          - cd frontend/todo-app
          - npm test


      - language: java
      
        jdk:
          - oraclejdk9
          
        install: true
        
        script: ./mvnw clean install
  
        script:
          # - cd restful-web-services
          - javac RestfulWebServicesApplication.java 


          