matrix:
  include:
      - language: node_js
        node_js:
          - "stable"
        cache:
        directories:
          - node_modules
        script:
          - cd frontend/todo-app
          - npm test

      - language: java
        jdk:
          - oraclejdk8
          - oraclejdk9
          - oraclejdk11
          - openjdk8
          - openjdk-ea
        
        script:
          - cd restful-web-services
          - javac RestfulWebServicesApplication.java 