language: node_js
language: java

node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd frontend/todo-app
  - npm test

jdk:
  - oraclejdk8
  - openjdk7
 
script:
  - cd restful-web-services
  - javac RestfulWebServicesApplication.java 