matrix:
  include:
      - language: node_js
        node_js:
          - "stable"
        cache:
        directories:
          - node_modules
        script:
          - cd frontend/todo-app
          - npm test

      # - language: java
      
      #   jdk:
      #     - oraclejdk8
      #     - openjdk8
  
      #   script:
      #     - cd restful-web-services
      #     - javac RestfulWebServicesApplication.java 


          